name = "emeditor-root-worker"
main = "build/index.js"
compatibility_date = "2026-05-05"

[build]
command = "cargo install -q \"worker-build@^0.8\" && worker-build --release --panic-unwind"

[vars]
BASE_URL = "https://www.emeditor.com"
BASE_HOSTNAME = "emeditor.com"

[env.dev.vars]
BASE_URL = "http://localhost:8787"
BASE_HOSTNAME = "localhost"

[assets]
directory = "./assets"
binding = "ASSETS"