name = "emeditor-root-worker"
main = "build/index.js"
compatibility_date = "2026-05-05"

[build]
command = "cargo install -q \"worker-build@^0.8\" && worker-build --release --panic-unwind"

[[routes]]
pattern = "emeditor.com/*"
zone_name = "emeditor.com"

[vars]
BASE_URL = "https://www.emeditor.com"
BASE_HOSTNAME = "emeditor.com"

[assets]
directory = "./assets"
binding = "ASSETS"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true
